export default function Head() {
    return (
      <>
        <title>Income and Expense Record</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </>
    );
  }
  